# DataSource Config
server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111
    url: jdbc:mysql://localhost:3306/cloud-study
  application:
    name: order
  cloud:
    nacos:
      server-addr: localhost:8848
