server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oneApp
          uri: lb://oneApp
          predicates:
            - Path=/one

        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**

        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**

        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
  main:
    web-application-type: reactive